Repository NUS-CRISP/CRISP, pull requests merged in 2025-03, with the labels that each got.

#301 Add Mock Trial User and Course Data for Tutorial (Github Data Only)
  backend/jobs/tutorialDataJob.ts
  multi-git-dashboard/.env.example
Labels: type: bug, priority: critical

#307 Add Notification Facade
  backend/clients/notificationFacadeClient.ts
  backend/clients/telegramClient.ts
  backend/controllers/notificationController.ts
  backend/jobs/notificationJob.ts
Labels: priority: high

#306 Ai insights
  backend/app.ts
  backend/jobs/aiInsightsJob.ts
  backend/jobs/githubJob.ts
  backend/jobs/publicGithubJob.ts
  backend/models/Course.ts
  backend/models/TeamData.ts
  backend/package-lock.json
  backend/package.json
  backend/services/courseService.ts
  multi-git-dashboard/src/components/code-analysis/CodeAnalysisAccordianItem.tsx
  multi-git-dashboard/src/components/code-analysis/CodeAnalysisOverview.tsx
  multi-git-dashboard/src/components/forms/CreateCourseForm.tsx
  multi-git-dashboard/src/components/forms/EditAIInsightsConfigForm.tsx
  multi-git-dashboard/src/components/views/CodeAnalysis.tsx
  multi-git-dashboard/src/lib/utils.ts
  shared/types/Course.ts
  shared/types/TeamData.ts
Labels: type: enhancement, priority: high, type: feature request

#314 Fix-student-name
  backend/jobs/tutorialDataJob.ts
  backend/services/courseService.ts
  backend/test/services/courseService.test.ts
Labels: type: bug, priority: high

#315 AI Insights Notification
  backend/jobs/aiInsightsJob.ts
Labels: priority: low, type: feature request

#342 Fix Submission Frontend Routing and Submission Drafts
  backend/services/submissionService.ts
  backend/test/services/submissionService.test.ts
  multi-git-dashboard/src/components/Navbar.tsx
  multi-git-dashboard/src/components/views/AssessmentInternalOverview.tsx
  multi-git-dashboard/src/components/views/EditAssessment.tsx
  multi-git-dashboard/src/components/views/TakeAssessmentInline.tsx
  multi-git-dashboard/src/lib/auth/utils.ts
  multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId].tsx
  multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId]/submission/[submissionId].tsx
Labels: priority: critical
